name       : openssl
version    : 1.0.2u
release    : 38
source     :
    - https://www.openssl.org/source/openssl-1.0.2u.tar.gz : ecd0c6ffb493dd06707d38b14bb4d8c2288bb7033735606569d8f90f89669d16
license    : OpenSSL
summary    : Legacy cryptographic tools required by many packages
description: |
    This is a legacy OpenSSL 1.0 series package. Building against this library is not supported and is only intended for legacy usecases or transitions between 1.0 series and 1.1.
component  :
    - system.base
    - devel : system.devel
emul32     : yes
patterns   :
    - devel:
      - /usr/lib64/openssl-1.0/libcrypto.a
      - /usr/lib64/openssl-1.0/libcrypto.so
      - /usr/lib64/openssl-1.0/libssl.a
      - /usr/lib64/openssl-1.0/libssl.so
      - /usr/lib64/openssl-1.0/pkgconfig
    - 32bit-devel:
      - /usr/lib32/openssl-1.0/libcrypto.a
      - /usr/lib32/openssl-1.0/libcrypto.so
      - /usr/lib32/openssl-1.0/libssl.a
      - /usr/lib32/openssl-1.0/libssl.so
      - /usr/lib32/openssl-1.0/pkgconfig
builddeps  :
    - pkgconfig32(zlib)
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    %patch -p1 < $pkgfiles/cflags.patch
    %patch -p1 < $pkgfiles/nodes.patch
    %patch -p1 < $pkgfiles/openssl-1.0-versioned-symbols.patch
    if [[ -z "${EMUL32BUILD}" ]]; then
        ./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib64/openssl-1.0 shared zlib-dynamic
    else
        ./Configure --prefix=/usr --openssldir=/etc/ssl --libdir=lib32/openssl-1.0 shared linux-elf zlib-dynamic
    fi
build      : |
    %make -j1
install    : |
    %make_install INSTALL_PREFIX="$installdir" MANDIR=/usr/share/man install_sw -j1
    mv $installdir/usr/include/openssl $installdir/usr/include/openssl-1.0/
    mv $installdir/%libdir%/openssl-1.0/lib{crypto,ssl}.so.1.0.0 $installdir/%libdir%/
    ln -sf ../libcrypto.so.1.0.0 $installdir/%libdir%/openssl-1.0/libcrypto.so
    ln -sf ../libssl.so.1.0.0 $installdir/%libdir%/openssl-1.0/libssl.so
    mv $installdir/usr/bin/openssl $installdir/usr/bin/openssl-1.0
    rm -rf $installdir/{etc,usr/bin/c_rehash}
    sed -e 's|/include$|/include/openssl-1.0|' -i $installdir/%libdir%/openssl-1.0/pkgconfig/*.pc
    rm -rf $installdir/usr/share
