name       : openssl
version    : 3.1.2
release    : 43
source     :
    - https://www.openssl.org/source/openssl-3.1.2.tar.gz : a0ce69b8b97ea6a35b96875235aa453b966ba3cba8af2de23657d8b6767d6539
license    : OpenSSL
summary    : Cryptographic tools required by many packages
description: |
    The OpenSSL package contains management tools and libraries relating to cryptography. These are useful for providing cryptography functions to other packages, such as OpenSSH, email applications and web browsers (for accessing HTTPS sites).
component  :
    - system.base
    - devel : system.devel
emul32     : yes
builddeps  :
    - pkgconfig32(zlib)
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    %patch -p1 -i $pkgfiles/0001-Use-OS-provided-copy-of-openssl.cnf-as-fallback.patch
    if [[ -z "${EMUL32BUILD}" ]]; then
        ./Configure --prefix=/usr --openssldir=/etc/ssl --libdir=lib64 shared no-ssl zlib-dynamic no-ssl2 no-ssl3 enable-ktls
    else
        ./Configure --prefix=/usr --openssldir=/etc/ssl --libdir=lib32 shared no-ssl zlib-dynamic no-ssl2 no-ssl3 enable-ktls linux-elf
    fi
build      : |
    %make
install    : |
    %make install_sw install_ssldirs install_man_docs DESTDIR="$installdir" INSTALL_PREFIX="$installdir"

    # Stateless (kinda)
    install -dm755 $installdir/usr/share/defaults/etc/ssl
    mv $installdir/etc/ssl/openssl.cnf $installdir/usr/share/defaults/etc/ssl/openssl.cnf
    rm -v $installdir/etc/ssl/openssl.cnf.dist
