name       : openssl
version    : 1.0.1i
release    : 26
source     :
    - https://www.openssl.org/source/openssl-1.0.2i.tar.gz : 9287487d11c9545b6efb287cdb70535d4e9b284dd10d51441d9b9963d000de6f
license    :
    - OpenSSL
summary    : Cryptographic tools required by many packages
component  :
    - system.base
    - devel : system.devel
builddeps  :
    - pkgconfig32(zlib)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
patterns   :
    - devel : /usr/share/man/man3
description: |
    The OpenSSL package contains management tools and libraries relating to cryptography. These are useful for providing cryptography functions to other packages, such as OpenSSH, email applications and web browsers (for accessing HTTPS sites).
setup      : |
    %patch -p1 < $pkgfiles/cflags.patch
    %patch -p1 < $pkgfiles/nodes.patch
    if [[ -z "${EMUL32BUILD}" ]]; then
        ./config --prefix=/usr --openssldir=/etc/ssl shared zlib-dynamic
    else
        ./Configure --prefix=/usr --openssldir=/etc/ssl --libdir=lib32 shared linux-elf zlib-dynamic
    fi
build      : |
    %make -j1
install    : |
    %make_install INSTALL_PREFIX="$installdir" MANDIR=/usr/share/man -j1
    mv $installdir/usr/share/man/man1/passwd.1 $installdir/usr/share/man/man1/passwd.openssl.1
    mv $installdir/usr/share/man/man3/threads.3 /usr/share/man/man3/threads.openssl.3
