name        : openssl
version     : 1.0.2h
release     : 20
source     :
    - https://www.openssl.org/source/openssl-1.0.2h.tar.gz : 1d4007e53aad94a5b2002fe045ee7bb0b3d98f1a47f8b2bc851dcd1c74332919
license     :
    - OpenSSL
summary     : Cryptographic tools required by many packages
component   :
    - system.base
    - devel: system.devel
patterns    :
    - devel : /usr/share/man/man3
optimize    : speed
description : |
    The OpenSSL package contains management tools and libraries relating to cryptography. These are useful for providing cryptography functions to other packages, such as OpenSSH, email applications and web browsers (for accessing HTTPS sites).
setup      : |
    %patch -p1 < $pkgfiles/cflags.patch
    %patch -p1 < $pkgfiles/nodes.patch
    ./config --prefix=/usr --openssldir=/etc/ssl shared zlib-dynamic 
build      : |
    %make -j1
install    : |
    %make_install INSTALL_PREFIX="$installdir" MANDIR=/usr/share/man -j1
    mv $installdir/usr/share/man/man1/passwd.1 $installdir/usr/share/man/man1/passwd.openssl.1
    mv $installdir/usr/share/man/man3/threads.3 /usr/share/man/man3/threads.openssl.3
profile    : |
    # Borrowed from clear
    ./apps/openssl speed 
