name       : openssl
version    : 1.0.2k
release    : 28
source     :
    - https://www.openssl.org/source/openssl-1.0.2k.tar.gz : 6b3977c61f2aedf0f96367dcfb5c6e578cf37e7b8d913b4ecb6643c3cb88d8c0
license    :
    - OpenSSL
summary    : Cryptographic tools required by many packages
component  :
    - system.base
    - devel : system.devel
builddeps  :
    - pkgconfig32(zlib)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
patterns   :
    - devel : /usr/share/man/man3
description: |
    The OpenSSL package contains management tools and libraries relating to cryptography. These are useful for providing cryptography functions to other packages, such as OpenSSH, email applications and web browsers (for accessing HTTPS sites).
setup      : |
    %patch -p1 < $pkgfiles/cflags.patch
    %patch -p1 < $pkgfiles/nodes.patch
    if [[ -z "${EMUL32BUILD}" ]]; then
        ./config --prefix=/usr --openssldir=/etc/ssl shared zlib-dynamic
    else
        ./Configure --prefix=/usr --openssldir=/etc/ssl --libdir=lib32 shared linux-elf zlib-dynamic
    fi
build      : |
    %make -j1
install    : |
    %make_install INSTALL_PREFIX="$installdir" MANDIR=/usr/share/man -j1
    mv $installdir/usr/share/man/man1/passwd.1 $installdir/usr/share/man/man1/passwd.openssl.1
    mv $installdir/usr/share/man/man3/threads.3 $installdir/usr/share/man/man3/threads.openssl.3
